package com.taskadapter.webui

import com.google.common.base.Charsets
import com.google.common.io.Files
import com.taskadapter.common.JsonUtil
import com.taskadapter.connector.common.FileNameGenerator
import net.liftweb.json.DefaultFormats
import org.slf4j.LoggerFactory

import java.io.{File, FilenameFilter}
import java.util.Optional
import scala.collection.JavaConverters._

class Storage(storageFolder: File, fileNamePrefix: String, fileNameExtension: String) {
  private val logger = LoggerFactory.getLogger(classOf[Storage])
  private val resultsFileFilter = new FilenameFilter {
    override def accept(dir: File, name: String): Boolean = name.startsWith(fileNamePrefix) && name.endsWith(fileNameExtension)
  }

  implicit val formats = DefaultFormats

  def get[T](elementId: String)(implicit man: Manifest[T]): Optional[T] = {
    val file = getFileById(elementId)
    val t = man.runtimeClass.asInstanceOf[Class[T]]
    if (file.exists()) {
      Optional.of(convertFileToObject(file, t))
    } else {
      Optional.empty()
    }
  }

  def getByFilter[T](filter: (T) => Boolean)(implicit man: Manifest[T]): Optional[T] = {
    val files = storageFolder.listFiles(resultsFileFilter)
    val t = man.runtimeClass.asInstanceOf[Class[T]]
    if (files != null) {
      files.foreach { file =>
        val obj = convertFileToObject(file, t)
        if (filter(obj)) {
          return Optional.of(obj)
        }
      }
    }
    Optional.empty()
  }

  def delete(elementId: String): Unit = {
    val file = getFileById(elementId)
    if (file.exists()) {
      file.delete()
    }
  }

  def deleteByFilter[T](filter: (T) => Boolean)(implicit man: Manifest[T]): Unit = {
    val files = storageFolder.listFiles(resultsFileFilter)
    val t = man.runtimeClass.asInstanceOf[Class[T]]
    if (files != null) {
      files.foreach { file =>
        val obj : T  = convertFileToObject(file, t)
        if (filter(obj)) {
          file.delete()
        }
      }
    }
  }

  def storeNewItemWithAutogeneratedName[T](result: T): Unit = {
    val file = FileNameGenerator.findSafeAvailableFileName(storageFolder, s"${fileNamePrefix}-%d.$fileNameExtension", 10000000)
    store(result, file)
  }

  def store[T](result: T, elementId: String): Unit = {
    val file = getFileById(elementId)
    store(result, file)
  }

  private def store[T](result: T, file: File): Unit = {
    val jsonString = JsonUtil.toJsonString(result)
    storageFolder.mkdirs()
    Files.write(jsonString, file, Charsets.UTF_8)
    logger.debug(s"Saved $result to ${file.getAbsolutePath}")
  }

  private def getFileById(elementId: String): File = {
    val relativeFileName = s"$fileNamePrefix-$elementId.$fileNameExtension"
    new File(storageFolder, relativeFileName)
  }

  def getItemsJava[T](clazz: Class[T] ): java.util.List[T] = {
    val files = storageFolder
      .listFiles(resultsFileFilter)
    if (files == null) {
      return java.util.List.of()
    }

    files.map(file => {
      var json = Files.toString(file, Charsets.UTF_8)
      JsonUtil.parseJsonString(json, clazz)
    }).toBuffer.asJava
  }

  private  def convertFileToObject[T](file: File, clazz: Class[T]): T = {
    import com.google.common.base.Charsets
    import com.google.common.io.Files

    val str = Files.toString(file, Charsets.UTF_8)
    JsonUtil.parseJsonString(str, clazz)
  }
}
