package com.taskadapter.launcher

import org.eclipse.jetty.server.Server
import org.eclipse.jetty.webapp.WebAppContext
import java.awt._
import java.io.File
import java.net.URI

object TALauncher {
  val PARAMETER_OPEN_TASK_ADAPTER_PAGE_IN_WEB_BROWSER = "--openTaskAdapterPageInWebBrowser"
  private val DEFAULT_HTTP_SERVER_PORT = 10842
  private val WEB_APPLICATION_ROOT_CONTEXT = "/ta"
  private val WAR_FOLDER = "./webui/build/libs"
  private val WAR_FILE_NAME = "webui.war"

  def main(args: Array[String]): Unit = {
    val portNumber = findPortNumberInArgs(args)
    System.out.println("Starting HTTP server on port " + portNumber)
    val server = new Server(portNumber)
    server.setHandler(new WebAppContext(getWarFileAbsolutePath, WEB_APPLICATION_ROOT_CONTEXT))
    try {
      server.start()
      while ( {
        !server.isStarted || !server.getHandler.isStarted
      }) try
        Thread.sleep(500)
      catch {
        case e: Exception =>         //logger.error(e);
      }
      val uri = "http://localhost:" + portNumber + WEB_APPLICATION_ROOT_CONTEXT
      System.out.println("=======================================================================")
      System.out.println("Task Adapter is started as a WEB-server running on port " + portNumber)
      System.out.println("Please OPEN your web browser with this URL: " + uri)
      System.out.println("=======================================================================")
      if (needToOpenBrowser(args)) {
        val desktop = Desktop.getDesktop
        desktop.browse(new URI(uri))
      }
      else System.out.println("Task Adapter launcher will open the browser automatically if you provide this parameter in the start script: " + PARAMETER_OPEN_TASK_ADAPTER_PAGE_IN_WEB_BROWSER)
    } catch {
      case e: Exception =>
        System.out.println("Error starting server: " + e.toString)
    }
  }

  def getWarFileAbsolutePath() : String = {
    // APP_HOME environment variable is set by the launcher script generated by Gradle.
    // it points to the root folder of the installed application.
    val appHome = System.getenv("APP_HOME")
    val folder = new File(appHome, WAR_FOLDER)
    val file = new File(folder, WAR_FILE_NAME)
    file.getAbsolutePath
  }

  def findPortNumberInArgs(args: Array[String]) : Int = {
    for (arg <- args) {
      val prefix = "--port="
      if (arg.startsWith(prefix)) {
        val portString = arg.substring(prefix.length)
        return portString.toInt
      }
    }
    DEFAULT_HTTP_SERVER_PORT
  }

  def needToOpenBrowser(args: Array[String]): Boolean = {
    args.contains(PARAMETER_OPEN_TASK_ADAPTER_PAGE_IN_WEB_BROWSER)
  }
}